---
title: "Tips and Tricks in R Programming Language"
author: "Nguyen Trung Nam"
date: "`r Sys.Date()`"
output: 
  html_document:
    number_sections: true
zoreto: True 
editor: 
  mode: source
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# CODING STYLE IN R

- Here, summary made from *http://adv-r.had.co.nz/Style.html*

## Notation and naming
### File names

-   File name should be meaningful and end in .R. If file names need to run in sequence, prefix them with numbers.

```         
# Good style: fit-models.R vs Bad style: foo.r
# Good style in sequence: 0-download.R 1-preprocess.R 2-modelling.R
```

### Objects names

-   Variable and function names should be lowercase, using underscore (\_) separate words within the names. In general, variable names should be nouns while function names should be verbs. Notes that it is crucial to avoid using names of existing functions or variables.

```         
# Good style: day_1 day_one
# Bad style: day1 DayOne
```

### Syntax

-   Spacing
    -   Place spaces around infix operators (=, +, -, \<-, etc) even in function calls, and always put spaces after a comma, never before it.This rule is except for : :, :: and :::, don't need put spaces around them.

```         
# Good style: average <- mean( feet / 12 + inches, na.rm = TRUE)
# Bad style: average <-mean( feet / 12 +inches, na.rm=TRUE) 
```

```         
- Place a space before left parentheses, except function call
```

```         
# Good style: if (debug) do(x) plot(x,y)
# Bad style: if (debug)do(x) plot (x,y)
```

```         
- Extra spacing (i.e., more than one space in a row) is ok if it enhances alignments of equal sign or assignment (\<-)
```

```         
# Good style: list( total = a + b + c 
                    mean = (a + b + c) / n)
# Bad style: list( total = a + b + c 
                   mean= (a + b + c) / n)
```

-   Curly braces
    -   an opening curly brace should never go on its own line and should always be followed by a new line. A closing curly brace should always go on its own line, unless its followed by else.
    -   Always indent the code inside curly braces.

```         
# Good

if (y < 0 && debug) {
  message("Y is negative")
}

if (y == 0) {
  log(x)
} else {
  y ^ x
}

if (y < 0 && debug)
message("Y is negative")


if (y == 0) {
  log(x)
}
else {
  y ^ x
}
```

-   Line length
    -   Strive to limit your code to 80 characters per line. This fits properly on a printed page with a reasonably sized font. If you find yourself running out of room, this is a good indication that you should encapsulate some of the work in a separate function.
-   Indentation
    -   When indenting your code, use two spaces. Never uses tab or mix tabs and spaces.
    -   The only exception is if a function definition runs over multiple lines. In that case, indent the second line to where the definition starts.

```         
long_function_nam <- function(a = "a long argument",
                              b = "another argument",
                              c = "another long argument") {
# As usual code is indented by two spaces
}
```

-   Assignment
    -   Use \<-, not =, for assignment.

```         
# Good
 a <- 5
# Bad
 b = 5
```

## Organization

### Commenting guidelines

-   Each line of a comment should begin with the comment symbol and a single space. \# Comment should explain the why, not the that.
-   Use commented lines of - and = to break up your files into easily readable chunks.

```         
# Load data -----------------

# Plot data -----------------
```
